wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: AlexNet
dataset:
  desc: null
  value: Fashion_Mnist(Resize 224)
epochs:
  desc: null
  value: 10
batch size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685338013.828029
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
